package:
  version: "{{ PROJECT_VERSION }}"
  name: 'gbasis'

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - libint =2.0.3 
  run:
    - libint =2.0.3 
test:
  commands:
    - conda inspect linkages gbasis

about:
  home: https://github.com/theochem/gbasis
  license: GPL3
