name: rtd-gbasis
channels:
  - theochem
dependencies:
  - libint
  - python=3.7
  - numpy
  - gcc_linux-64
  - gxx_linux-64
  - cython
  - pip:
      - breathe
      - exhale
      - sphinx-autodoc-typehints
      - sphinxcontrib-mermaid
      - sphinxcontrib-napoleon