linters:
#  - cppcheck:
  - cpplint:
      script: ./cpplint.py
  - doxygen:
  - header:
  - header:
      filefilter: ['+ *.cpp', '+ *.h', '+ *.h.in']
      comment: '// '
      shebang:
      extra: []
  - whitespace:
