package:
  version: "{{ PROJECT_VERSION }}"
  name: 'python-gbasis'

source:
  path: ../

build:
  number: 0

requirements:
  host:
    - python ={{ MYCONDAPY }}
    - cython >=0.24.1
    - libint =2.0.3
    - numpy
    - setuptools
    - nose
    - cxx-gbasis >=0.2.1
  run:
    - python >=3
    - numpy
    - scipy
    - nose
test:
  requires:
    - nose
  commands:
    - nosetests -v --detailed-errors gbasis
    - conda inspect linkages python-gbasis

about:
  home: https://github.com/theochem/gbasis
  license: GPL3
