package:
  version: "{{ PROJECT_VERSION }}"
  name: 'gbasis'

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python >=3
    - numpy
    - scipy
    - cython >=0.24.1
    - setuptools
    - nose
    - libint
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python >=3
    - numpy
    - scipy
    - nose
    - libint
  test:
    commands:
      - conda inspect linkages gbasis

about:
  home: https://github.com/theochem/gbasis
  license: GNU Version 3
