package:
  version: "{{ PROJECT_VERSION }}"
  name: 'gbasis'

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python ={{ MYCONDAPY }}
    - libint =2.0.3 
    - cython >=0.24.1
    - numpy
    - setuptools
    - nose
  run:
    - python >=3
    - numpy
    - scipy
    - nose
    - libint =2.0.3
test:
  requires:
    - nose
  commands:
    - nosetests -v --detailed-errors gbasis
    - conda inspect linkages gbasis

about:
  home: https://github.com/theochem/gbasis
  license: GNU Version 3
